name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  pa11y-scan:
    # Pinned to 20.04 because pa11y-ci fails to run on 22.04 
    # See the discussion on https://github.com/pa11y/pa11y-ci/issues/198
    # and https://github.com/pa11y/pa11y/issues/651 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install node dependencies
        run: npm install
      - name: Accessibility scan
        run: npm run pa11y
